Add new firmware target with wider range drivers
QubesOS/qubes-builder-debian pull request #35
Opened 2019-07-29 15:17 UTC by unman

QubesOS/qubes-issues#5123

Needs additional "firmware" target set in qubes-builder, currently waiting on merge of QubesOS/qubes-builder/pull/84

2019-08-01 23:56 UTC, marmarek commented
What about license prompts for other packages? See https://github.com/QubesOS/qubes-issues/issues/5123#issuecomment-509363807

2019-08-02 14:45 UTC, marmarek requested changes
What about license prompts for other packages? See https://github.com/QubesOS/qubes-issues/issues/5123#issuecomment-509363807

2019-08-16 12:48 UTC, unman commented
> What about license prompts for other packages? 

Not needed:no prompts.
I have included the only necessary one,

2019-09-06 02:10 UTC, marmarek approved these changes

2019-09-06 02:14 UTC, merged